Support python3 in brightness script

diff --git a/bin/brightness b/bin/brightness
--- a/bin/brightness
+++ b/bin/brightness
@@ -36,7 +36,95 @@
 ###/doc
 
 
-##bash-libs: syntax-extensions.sh @ 1d3814ad (2.1.13)
+##bash-libs: out.sh @ de7210ba (2.1.21.3)
+
+### Console output handlers Usage:bbuild
+#
+# Write data to console stderr using colouring
+#
+###/doc
+
+### out:info MESSAGE Usage:bbuild
+# print a green informational message to stderr
+###/doc
+function out:info {
+    echo "$CGRN$*$CDEF" 1>&2
+}
+
+### out:warn MESSAGE Usage:bbuild
+# print a yellow warning message to stderr
+###/doc
+function out:warn {
+    echo "${CBYEL}WARN: $CYEL$*$CDEF" 1>&2
+}
+
+### out:defer MESSAGE Usage:bbuild
+# Store a message in the output buffer for later use
+###/doc
+function out:defer {
+    OUTPUT_BUFFER_defer[${#OUTPUT_BUFFER_defer[@]}]="$*"
+}
+
+# Internal
+function out:buffer_initialize {
+    OUTPUT_BUFFER_defer=(:)
+}
+out:buffer_initialize
+
+### out:flush HANDLER ... Usage:bbuild
+#
+# Pass the output buffer to the command defined by HANDLER
+# and empty the buffer
+#
+# Examples:
+#
+# 	out:flush echo -e
+#
+# 	out:flush out:warn
+#
+# (escaped newlines are added in the buffer, so `-e` option is
+#  needed to process the escape sequences)
+#
+###/doc
+function out:flush {
+    [[ -n "$*" ]] || out:fail "Did not provide a command for buffered output\n\n${OUTPUT_BUFFER_defer[*]}"
+
+    [[ "${#OUTPUT_BUFFER_defer[@]}" -gt 1 ]] || return 0
+
+    for buffer_line in "${OUTPUT_BUFFER_defer[@]:1}"; do
+        "$@" "$buffer_line"
+    done
+
+    out:buffer_initialize
+}
+
+### out:fail [CODE] MESSAGE Usage:bbuild
+# print a red failure message to stderr and exit with CODE
+# CODE must be a number
+# if no code is specified, error code 127 is used
+###/doc
+function out:fail {
+    local ERCODE=127
+    local numpat='^[0-9]+$'
+
+    if [[ "$1" =~ $numpat ]]; then
+        ERCODE="$1"; shift || :
+    fi
+
+    echo "${CBRED}ERROR FAIL: $CRED$*$CDEF" 1>&2
+    exit $ERCODE
+}
+
+### out:error MESSAGE Usage:bbuild
+# print a red error message to stderr
+#
+# unlike out:fail, does not cause script exit
+###/doc
+function out:error {
+    echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
+}
+
+##bash-libs: syntax-extensions.sh @ de7210ba (2.1.21.3)
 
 ### Syntax Extensions Usage:syntax
 #
@@ -157,7 +245,7 @@ syntax-extensions:use:local() {
 args:use:local() {
     syntax-extensions:use:local "$@"
 }
-##bash-libs: tty.sh @ 1d3814ad (2.1.13)
+##bash-libs: tty.sh @ de7210ba (2.1.21.3)
 
 ### tty.sh Usage:bbuild
 # Get information on the current terminal session.
@@ -187,7 +275,7 @@ tty:is_multiplexer() {
     [[ -n "${TMUX:-}" ]] || [[ "${TERM:-}" = screen ]]
 }
 
-##bash-libs: colours.sh @ 1d3814ad (2.1.13)
+##bash-libs: colours.sh @ de7210ba (2.1.21.3)
 
 ### Colours for terminal Usage:bbuild
 # A series of shorthand colour flags for use in outputs, and functions to set your own flags.
@@ -196,7 +284,7 @@ tty:is_multiplexer() {
 #
 # Example:
 # 	
-# 	echo "${CRED}Some red text ${CBBLU} some blue text. $CDEF Some text in the terminal's default colour")
+# 	echo "${CRED}Some red text ${CBBLU} some blue text. $CDEF Some text in the terminal's default colour"
 #
 # Preconfigured colours available:
 #
@@ -206,8 +294,8 @@ tty:is_multiplexer() {
 # CBLU, CBBLU, HLBLU -- blue, bright blue, highlight blue
 # CPUR, CBPUR, HLPUR -- purple, bright purple, highlight purple
 # CTEA, CBTEA, HLTEA -- teal, bright teal, highlight teal
-# CBLA, CBBLA, HLBLA -- black, bright red, highlight red
-# CWHI, CBWHI, HLWHI -- white, bright red, highlight red
+# CBLA, CBBLA, HLBLA -- black, "bright" black, highlight black
+# CWHI, CBWHI, HLWHI -- white, "bright" white, highlight white
 #
 # Modifiers available:
 #
@@ -219,18 +307,25 @@ tty:is_multiplexer() {
 # 
 # Resets available:
 #
-# CNORM -- turn off bright or dim, without affecting other modifiers
+# CBNRM -- turn off bright or dim, without affecting other modifiers
 # ULOFF -- turn off highlighting
-# RVOFF -- turn off inverse
+# RVOFF -- turn off reverse colours
 # SKOFF -- turn off strikethrough
 # HLOFF -- turn off highlight
 #
-# CDEF -- turn off all colours and modifiers(switches to the terminal default)
+# CDEF -- turn off all colours and modifiers (switches to the terminal default)
 #
 # Note that highlight and underline must be applied or re-applied after specifying a colour.
 #
 # If the session is detected as being in a pipe, colours will be turned off.
 #   You can override this by calling `colours:check --color=always` at the start of your script
+#
+#
+# /!\ SPELLING /!\
+#
+# For historic reasons, "colours.sh" was named using British spelling; however some options use American spelling to match expectations from using other tools like `ls` for example.
+#
+# Consider that in the future, this will likely be changed for consistency - this library would become fully Ameriquified and the library renamed to 'colors.sh' and all functions will start with 'color:'.
 #
 ###/doc
 
@@ -246,6 +341,8 @@ tty:is_multiplexer() {
 #   }
 #
 #   main "$@"
+#
+# Note use of American spelling in the option itself.
 #
 ###/doc
 colours:check() {
@@ -341,6 +438,14 @@ colours:define() {
 
 }
 
+### colours:remove Usage:bbuild
+# Pipe function to remove ANSI colour bytes
+###/doc
+colours:remove() {
+    local _b=$'\033'
+    sed -r "s/${_b}\[[0-9;]+m//g"
+}
+
 colours:auto() {
     if tty:is_pipe ; then
         COLOURS_ON=false
@@ -353,95 +458,7 @@ colours:auto() {
 }
 
 colours:auto
-
-##bash-libs: out.sh @ 1d3814ad (2.1.13)
-
-### Console output handlers Usage:bbuild
-#
-# Write data to console stderr using colouring
-#
-###/doc
-
-### out:info MESSAGE Usage:bbuild
-# print a green informational message to stderr
-###/doc
-function out:info {
-    echo "$CGRN$*$CDEF" 1>&2
-}
-
-### out:warn MESSAGE Usage:bbuild
-# print a yellow warning message to stderr
-###/doc
-function out:warn {
-    echo "${CBYEL}WARN: $CYEL$*$CDEF" 1>&2
-}
-
-### out:defer MESSAGE Usage:bbuild
-# Store a message in the output buffer for later use
-###/doc
-function out:defer {
-    OUTPUT_BUFFER_defer[${#OUTPUT_BUFFER_defer[@]}]="$*"
-}
-
-# Internal
-function out:buffer_initialize {
-    OUTPUT_BUFFER_defer=(:)
-}
-out:buffer_initialize
-
-### out:flush HANDLER ... Usage:bbuild
-#
-# Pass the output buffer to the command defined by HANDLER
-# and empty the buffer
-#
-# Examples:
-#
-# 	out:flush echo -e
-#
-# 	out:flush out:warn
-#
-# (escaped newlines are added in the buffer, so `-e` option is
-#  needed to process the escape sequences)
-#
-###/doc
-function out:flush {
-    [[ -n "$*" ]] || out:fail "Did not provide a command for buffered output\n\n${OUTPUT_BUFFER_defer[*]}"
-
-    [[ "${#OUTPUT_BUFFER_defer[@]}" -gt 1 ]] || return 0
-
-    for buffer_line in "${OUTPUT_BUFFER_defer[@]:1}"; do
-        "$@" "$buffer_line"
-    done
-
-    out:buffer_initialize
-}
-
-### out:fail [CODE] MESSAGE Usage:bbuild
-# print a red failure message to stderr and exit with CODE
-# CODE must be a number
-# if no code is specified, error code 127 is used
-###/doc
-function out:fail {
-    local ERCODE=127
-    local numpat='^[0-9]+$'
-
-    if [[ "$1" =~ $numpat ]]; then
-        ERCODE="$1"; shift || :
-    fi
-
-    echo "${CBRED}ERROR FAIL: $CRED$*$CDEF" 1>&2
-    exit $ERCODE
-}
-
-### out:error MESSAGE Usage:bbuild
-# print a red error message to stderr
-#
-# unlike out:fail, does not cause script exit
-###/doc
-function out:error {
-    echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
-}
-##bash-libs: patterns.sh @ 1d3814ad (2.1.13)
+##bash-libs: patterns.sh @ de7210ba (2.1.21.3)
 
 ### Useful patterns Usage:bbuild
 #
@@ -465,6 +482,129 @@ export PAT_num='^[0-9]+$'
 export PAT_cvar='^[a-zA-Z_][a-zA-Z0-9_]*$'
 export PAT_filename='^[a-zA-Z0-9_. -]+$'
 export PAT_email="[a-zA-Z0-9_.+-]+@[a-zA-Z0-9][a-zA-Z0-9.-]+\.[a-z]+"
+
+##bash-libs: debug.sh @ de7210ba (2.1.21.3)
+
+### Debug lib Usage:bbuild
+#
+# Debugging tools and functions.
+#
+# You need to activate debug mode using debug:activate command at the start of your script
+#  (or from whatever point you wish it to activate)
+#
+###/doc
+
+### Environment Variables Usage:bbuild
+#
+# DEBUG_mode : set to 'true' to enable debugging output
+#
+###/doc
+
+: ${DEBUG_mode=false}
+
+### debug:print MESSAGE Usage:bbuild
+# print a blue debug message to stderr
+# only prints if DEBUG_mode is set to "true"
+###/doc
+function debug:print {
+    [[ "$DEBUG_mode" = true ]] || return 0
+    echo "${CBBLU}DEBUG: $CBLU$*$CDEF" 1>&2
+}
+
+### debug:dump [MARKER] Usage:bbuild
+#
+# Pipe the data coming through stdin to stdout (as if it weren't there at all)
+#
+# If debug mode is on, *also* write the same data to stderr, each line preceded by MARKER
+#
+# Insert this function into pipes to see their output when in debugging mode
+#
+#   sed -r 's/linux|unix/*NIX/gi' myfile.txt | debug:dump | lprint
+#
+# Or use this to mask a command's output unless in debug mode
+#
+#   which binary 2>&1 | debug:dump
+#
+###/doc
+function debug:dump {
+    if [[ "$DEBUG_mode" = true ]]; then
+        local MARKER="${1:-DEBUG: }"; shift || :
+
+        cat - | sed -r "s/^/$MARKER/" | tee -a /dev/stderr | sed -r "s/^$MARKER//"
+    else
+        cat -
+    fi
+}
+
+### debug:break MESSAGE Usage:bbuild
+#
+# Add break points to a script
+#
+# Requires `DEBUG_mode` set to true
+#
+# When the script runs, the message is printed with a prompt, and execution pauses.
+#
+# Press return to continue execution.
+#
+# Type a variable name, with leading `$`, to dump it, e.g. `$myvar`
+#
+# Type a variable name, with leading `$`, followed by an assignment to change its value, e.g. `$myvar=new value`
+#  the new value will be seen by the script.
+#
+# Type 'env' to dump the current environment variables.
+#
+# Type `exit`, `quit` or `stop` to stop the program. If the breakpoint is in a subshell,
+#  execution from after the subshell will be resumed.
+#
+###/doc
+
+function debug:break {
+    [[ "$DEBUG_mode" = true ]] || return 0
+    local reply
+
+    while true; do
+        read -p "${CRED}BREAKPOINT: $* >$CDEF " reply
+        if [[ "$reply" =~ quit|exit|stop ]]; then
+            echo "${CBRED}ABORT${CDEF}" >&2
+            exit 127
+
+        elif [[ "$reply" = env ]]; then
+            env |sed 's//^[/g' |debug:dump "--- "
+
+        elif [[ "$reply" =~ ^\$ ]]; then
+            debug:_break_dump "${reply:1}" || :
+
+        elif [[ -z "$reply" ]]; then
+            return 0
+        else
+            debug:print "'quit','exit' or 'stop' to abort; '\$varname' to see a variable's contents; '\$varname=new value' to assign a new value for run time; <Enter> to continue"
+        fi
+    done
+}
+
+debug:_break_dump() {
+    local inspectable="$1"
+    local varname="$1"
+    local varval
+
+    if [[ "$inspectable" =~ = ]]; then
+        varname="${inspectable%%=*}"
+        varval="${inspectable#*=}"
+    fi
+
+    [[ "$varname" =~ $PAT_cvar ]] || {
+        debug:print "${CRED}Invalid var name '$varname'"
+        return 1
+    }
+
+    declare -n inspect="$varname"
+
+    if [[ "$inspectable" =~ = ]]; then
+        inspect="$varval"
+    else
+        echo "$inspect"
+    fi
+}
 
 ### Formatting library Usage:bbuild
 #
@@ -492,7 +632,11 @@ format:columns() {
     . <(args:use:local ?sep -- "$@") ; 
     [[ -n "$sep" ]] || sep=$'\t'
 
-    column -t -s "$sep"
+    if tty:is_pipe; then
+        cat -
+    else
+        column -t -s "$sep"
+    fi
 }
 
 ### format:wrap Usage:bbuild
@@ -508,12 +652,17 @@ format:columns() {
 
 format:wrap() {
     . <(args:use:local ?cols -- "$@") ; 
-    [[ -n "$cols" ]] || cols="$(tput cols)"
     [[ "$cols" =~ $PAT_num ]] || return 1
-    fold -w "$cols" -s
+
+    if tty:is_pipe; then
+        cat -
+    else
+        [[ -n "$cols" ]] || cols="$(tput cols)"
+        fold -w "$cols" -s
+    fi
 }
 
-##bash-libs: autohelp.sh @ 1d3814ad (2.1.13)
+##bash-libs: autohelp.sh @ de7210ba (2.1.21.3)
 
 ### Autohelp Usage:bbuild
 #
@@ -745,7 +894,7 @@ fi
 
 function noargs {
 	curbright=$(cat "$BRIGHTPATH")
-	cbidx=$(python -c "import math ; prec = 10.0 ; print str(math.ceil( (10*prec * $curbright) / $MAXBRIGHT)/prec )")
+	cbidx=$(python -c "import math ; prec = 10.0 ; print( str(math.ceil( (10*prec * $curbright) / $MAXBRIGHT)/prec ))")
 
 	out:info "Current brightness index: $cbidx (raw value: $curbright)"
 	exit
@@ -776,7 +925,7 @@ while [[ -n "$*" ]]; do
 	if [[ ! "$mybright" =~ $(echo '^[0-9]+(\.[0-9]+)?$') ]] || python -c "$mybright > 10 or exit(1)" ; then
 		out:fail "Provide a numerical value from 0 to 10 only"
 	fi
-	mybright=$(python -c "print int(($mybright/10.0)*$MAXBRIGHT)")
+	mybright=$(python -c "print( int(($mybright/10.0)*$MAXBRIGHT))")
 
 
 	debug:print "Setting brightness $mybright"
