Check for EDITOR, gpg and config
* Check for editor variable - use nano if not set, abort if no nano
* Check for gpg executable, warn if not present
* Check if --help invoked, if so, printhelp even if no config present
*

diff --git a/bin/sendme b/bin/sendme
--- a/bin/sendme
+++ b/bin/sendme
@@ -1,21 +1,40 @@
 #!/bin/bash
-
-set -euo pipefail
-
 CDEF='[0m'
 CRED='[1;31m'
 CGRN='[1;32m'
 CYEL='[1;33m'
 CBLU='[1;34m'
+
+GCMD=
+if [[ $(which gpg2 > /dev/null 2>&1; echo $?) -lt 1 ]]; then
+	GCMD=gpg2
+elif [[ $(which gpg > /dev/null 2>&1; echo $?) -lt 1 ]]; then
+	GCMD=gpg
+else
+	echo "${CYEL}No gpg2/gpg command found. Suggestion: install ${CBLU}apt-get install gnupg2${CDEF}"
+fi
+
+if [[ -z "$EDITOR" ]]; then
+	if [[ -f /usr/bin/nano ]]; then
+		echo "${CYEL}\$EDITOR variable not set. Using nano${CDEF}"
+		export EDITOR=/usr/bin/nano
+	else
+		echo "${CRED}\$EDITOR variable not set. Abort.${CDEF}"
+		exit 97
+	fi
+fi
+
+set -euo pipefail
+
+helppat='-h|--help'
 FILES=
 FROM=
 RCPT=
-. $HOME/.config/sendme
 
 function printhelp {
 cat <<EOF
 
-        ${CBLU}sendme${CDEF}
+	${CBLU}sendme${CDEF}
 
 Friendly terminal email sending tool.
 
@@ -29,8 +48,8 @@ You can define the "FROM" and "RCPT" shell variabels in a config file - example
 
     ${CGRN}cat $HOME/.config/sendme
 ${CYEL}
-        RCPT=me@example.com
-        FROM=noreply@bogus.foo
+	RCPT=me@example.com
+	FROM=noreply@bogus.foo
 ${CDEF}
 You can still change these on an ad-hoc basis when running the command.
 
@@ -42,13 +61,14 @@ Future versions will support:
 
 EOF
 }
-helppat='-h|--help'
 MSGFILE="/tmp/sendme-message-$(date +'%F.%T')"
 ASCFILE="$MSGFILE.asc"
 
+[[ "$@" =~ $helppat ]] && { printhelp ; exit ; } # allow printing help before loading config
+. "$HOME"/.config/sendme
+
 [[ ! -z "$@" ]] && { echo -e "\n\n\n++++++\nAttachment MD5 sums:\n" > "$MSGFILE" ; }
 for xfile in "$@"; do
-	[[ "$xfile" =~ $helppat ]] && { printhelp ; exit ; }
 	[[ ! -f "$xfile" ]] && { "${CRED}$xfile does not exist.${CDEF}" ; exit 2 ; }
 	FILES="$FILES -A $xfile"
 	md5sum "$xfile" >> "$MSGFILE" # Linux only. FIXME need to adapt for cygwin and OS.X
@@ -67,7 +87,7 @@ if [[ -n "$RES" ]]; then
 	$EDITOR "$MSGFILE" # use the EDITOR variable
 	read -p "Sign with GPG? y/N> " SIG
 	[[ "$SIG" = y ]] && {
-		gpg --output="$ASCFILE" --clearsign "$MSGFILE"
+		"$GCMD" --output="$ASCFILE" --clearsign "$MSGFILE"
 		MSGFILE="$ASCFILE"
 	}
 	mail -s "$RES" -r "$FROM" $FILES $RCPT < "$MSGFILE"
