Various adjustments, add installer for commonly desirable scripts

diff --git a/bin/wifi b/bin/wifi
--- a/bin/wifi
+++ b/bin/wifi
@@ -1,102 +1,36 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-### sendme Usage:help
-# 
-# Friendly terminal email sending tool.
-# 
-# Supports GPG-sgning of message.
-# 
-#     sendme [FILES]
-# 
-# Specify files on the command line to be attached to the mailer program.
-# 
-# You can define the "FROM" and "RCPT" shell variabels in ~/.config/sendme - example
-# 
-#     cat $HOME/.config/sendme
+### wifi Usage:help
 #
-# 	RCPT=me@example.com
-# 	FROM=noreply@bogus.foo
-# 
-# You can still change these on an ad-hoc basis when running the command.
-# 
-# FUTURE
-# 
-# Future versions intend to support:
-# * specifying a template to use
-###/doc
-
-##bash-libs: bincheck.sh @ 1d3814ad (2.1.13)
-
-### bincheck:get COMMANDS ... Usage:bbuild
+# Some simple wifi controls wrapping around nmcli
 #
-# Return the first existing binary
+# USAGE
+# =====
 #
-# Useful for finding an appropriate binary when you know
-# different systems may supply binaries under different names.
+# 	nmcli [ list | start | stop | restart | connect ACCESSPOINT [PASSWORD] | forget ACCESSPOINT ]
 #
-# Returns the full path from `which` for the first executable
-# encountered.
+# list
+# 	Lists available access points
 #
-# Example:
+# start
+# 	Activates the wifi device
 #
-# 	bincheck:get markdown_py markdown ./mymarkdown
+# stop
+# 	Stop the wifi device
 #
-# Tries in turn to get a `markdown_py`, then a `markdown`, and then a local `./mymarkdown`
+# restart
+# 	Restart the wifi device
+#
+# connect ACCESSPOINT [PASSWORD]
+# 	Connect to the given access point, optionally providing a password
+# 	If the password is provided, it is saved for future use.
+# 	If the password is not provided, but a saved password exists, that saved password is used.
+#
+# forget ACCESSPOINT
+# 	Forget the access point and password
 #
 ###/doc
 
-bincheck:get() {
-    local BINEXE=
-    for binname in "$@"; do
-        # Some implementations of `which` print error messages
-        # Not useful here.
-        BINEXE=$(which "$binname" 2>/dev/null)
-
-        if [[ -n "$BINEXE" ]]; then
-            echo "$BINEXE"
-            return 0
-        fi
-    done
-    return 1
-}
-
-### bincheck:has NAMES ... Usage:bbuild
-#
-# Determine if at least one of the binaries listed is present and installed on the system
-#
-###/doc
-
-bincheck:has() {
-    [[ -n "$(bincheck:get "$@")" ]]
-}
-
-### bincheck:path NAME Usage:bbuild
-#
-# Determine the actual path to the command
-#
-# Relative paths are not expanded.
-#
-###/doc
-
-bincheck:path() {
-    local binname="$1"; shift || :
-
-    [[ "$binname" =~ / ]] && { 
-        # A relative path cannot be resolved, just check existence
-        [[ -e "$binname" ]] && echo "$binname" || return 1
-
-    } || binname="$(which "$binname" 2>/dev/null)"
-
-    # `which` failed
-    [[ -n "$binname" ]] || return 1
-
-    [[ -h "$binname" ]] && {
-
-        local pointedname="$(ls -l "$binname"|grep -oP "$binname.+"|sed "s|$binname -> ||")"
-        bincheck:path "$pointedname" ; return "$?"
-    
-    } || echo "$binname"
-}
 
 ##bash-libs: syntax-extensions.sh @ 1d3814ad (2.1.13)
 
@@ -772,202 +706,95 @@ autohelp:check:section() {
     done
 }
 
-##bash-libs: askuser.sh @ 1d3814ad (2.1.13)
+SEP=$'\033'
 
-### askuser Usage:bbuild
-# Present the user with questions on stderr
-###/doc
-
-yespat='^(yes|YES|y|Y)$'
-numpat='^[0-9]+$'
-rangepat='[0-9]+,[0-9]+'
-listpat='^[0-9 ]+$'
-blankpat='^ *$'
-
-### askuser:confirm Usage:bbuild
-# Ask the user to confirm a closed question. Defaults to no
-#
-# returns 0 on successfully match 'y' or 'yes'
-# returns 1 otherwise
-###/doc
-function askuser:confirm {
-    read -p "$* [y/N] > " 1>&2
-    if [[ "$REPLY" =~ $yespat ]]; then
-        return 0
-    else
-        return 1
-    fi
-}
-
-### askuser:ask Usage:bbuild
-# Ask the user to provide some text
-#
-# Echoes out the entered text
-###/doc
-function askuser:ask {
-    read -p "$* : " 1>&2
-    echo "$REPLY"
-}
-
-### askuser:password Usage:bbuild
-# Ask the user to enter a password (does not echo what is typed)
-#
-# Echoes out the entered text
-###/doc
-function askuser:password {
-    read -s -p "$* : " 1>&2
-    echo >&2
-    echo "$REPLY"
-}
-
-### askuser:choose_multi Usage:bbuild
-# Allows the user to choose from multiple choices
-#
-# askuser:chose_multi MESG CHOICESTRING
-#
-#
-# MESG is a single string token that will be displayed as prompt
-#
-# CHOICESTRING is a comma-separated, or newline separated, or "\\n"-separated token string
-#
-# Equivalent strings include:
-#
-# * `"a\\nb\\nc"` - quoted and explicit newline escapes
-# * `"a,b,c"` - quoted and separated with commas
-# * `a , b , c` - not quoted, separated by commas
-# * `a`, `b` and `c` on their own lines
-#
-# User input:
-#
-# User can choose by selecting
-#
-# * a single item by number
-# * a range of numbers (4,7 for range 4 to 7)
-# * or a string that matches the pattern
-#
-# All option lines that match will be returned, one per line
-#
-# If the user selects nothing, then function returns 1 and an empty stdout
-###/doc
-function askuser:choose_multi {
-    local mesg=$1; shift || :
-    local choices=$(echo "$*"|sed -r 's/ *, */\n/g')
-
-    out:info "$mesg:" 
-    local choicelist="$(echo -e "$choices"|grep -E '^' -n| sed 's/:/: /')"
-    echo "$choicelist" 1>&2
-    
-    local sel=$(askuser:ask "Choice")
-    if [[ "$sel" =~ $blankpat ]]; then
-        return 1
-
-    elif [[ "$sel" =~ $numpat ]] || [[ "$sel" =~ $rangepat ]]; then
-        echo -e "$choices" | sed -n "$sel p"
-    
-    elif [[ "$sel" =~ $listpat ]]; then
-        echo "$choicelist" | grep -E "^${sel// /|}:" | sed -r 's/^[0-9]+: //'
-
-    else
-        echo -e "$choices"  |grep -E "$(echo "$sel"|tr " " '|')"
-    fi
-    return 0
-}
-
-### askuser:choose Usage:bbuild
-# Ask the user to choose an item
-#
-# Like askuser:choose_multi, but will loop if the user selects more than one item
-#
-# If the user provides no entry, returns 1
-#
-# If the user chooses one item, that item is echoed to stdout
-###/doc
-function askuser:choose {
-    local mesg=$1; shift || :
-    while true; do
-        local thechoice="$(askuser:choose_multi "$mesg" "$*")"
-        local lines=$(echo -n "$thechoice" | grep '$' -c)
-        if [[ $lines = 1 ]]; then
-            echo "$thechoice"
-            return 0
-        elif [[ $lines = 0 ]]; then
-            return 1
-        else
-            out:warn "Too many results"
-        fi
-    done
-}
-
-GCMD="$(bincheck:get gpg2 gpg)"
-if [[ -z "${GCMD+x}" ]]; then
-	out:warn "No gpg2/gpg command found. Suggestion: install gnupg2"
-elif [[ -z "$("$GCMD" --list-keys|egrep '^pub'|grep -v "expired")" ]]; then
-	out:warn "No GPG active keys currently installed ['$GCMD --list-keys']"
-	out:warn "Run '$GCMD --gen-key' to generate keys."
-	out:warn "---"
-
-	# Treat as if no GPG support (do not prompt, etc)
-	GCMD=
+if [[ -z "$(which nmcli)" ]]; then
+	out:fail 'Required program `nmcli` not found.'
 fi
 
-# FIXME prioritize with a stronger hash
-HASHCMD=$(bincheck:get sha512sum sha256sum md5sum md5)
-
-if ! bincheck:has mailx; then
-	out:fail 96 "No mailx command found."
+if [[ -z "$*" ]]; then
+	out:info "Raw wifi status\n"
+	out:info "$(nmcli connection show --active | grep wireless)\n"
+	exit
 fi
 
-if [[ -z "$EDITOR" ]]; then
-	if bincheck:has nano; then
-		out:warn "\$EDITOR variable not set. Using nano"
-		export EDITOR="$(bincheck:get nano)"
+WIFICMD="$1" ; shift
+
+function newconn {
+	WIFI_AP="$1"; shift
+	WIFI_PW="$1"; shift
+
+	out:info "Trying to establish new connection ..."
+
+	if [[ -n "$WIFI_PW" ]]; then
+		nmcli device wifi connect "$WIFI_AP" password "$WIFI_PW" ; RES=$?
 	else
-		out:fail 96 "\$EDITOR variable not set ; nano not available"
+		nmcli device wifi connect "$WIFI_AP" ; RES="$?"
 	fi
-fi
 
-FILES=
-FROM=
-RCPT=
-ATCH=$( [[ $(man mailx | grep 'mailutils' -c) -gt 0 ]] && echo "-A" ; [[ $(man mailx | grep 'Heirloom' -c) -gt 0 ]] && echo "-a" ; )
-[[ -z "$ATCH" ]] && out:fail 96 "Could not determine mailx flavour."
+	return "$RES"
+}
 
-set -euo pipefail
+function oldconn {
+	WIFI_AP="$1"; shift
+	out:info "Trying old connections ..."
 
-MSGFILE="/tmp/sendme-message-$(date +'%F.%T')"
-ASCFILE="$MSGFILE.asc"
+	nmcli connection up "$WIFI_AP" ; RES=$?
 
-. "$HOME"/.config/sendme
+	return "$RES"
+}
 
-[[ ! -z "$@" ]] && { echo -e "\n\n\n++++++\nAttachment [$HASHCMD] sums:\n" > "$MSGFILE" ; }
+case "$WIFICMD" in
+	restart)
+		debug:print Deactivating wifi
+		nmcli radio wifi off
 
-for xfile in "$@"; do
-	[[ ! -f "$xfile" ]] && out:fail 2 "$xfile does not exist."
+		debug:print Re-activating wifi
+		nmcli radio wifi on
 
-	FILES="$FILES $ATCH $xfile"
-	"$HASHCMD" "$xfile" >> "$MSGFILE"
-done
+		out:info Done.
+		;;
+	stop)
+		debug:print Deactivating wifi
+		nmcli radio wifi off
+		out:info Done.
+		;;
+	start)
+		debug:print Re-activating wifi
+		nmcli radio wifi on
+		out:info Done.
+		;;
+	connect)
+		nmcli device wifi rescan
+		WIFI_AP="$1"; shift
+		WIFI_PW="$1"; shift
 
-[[ -z "$FILES" ]] && out:warn "No files specified"
+		if [[ -z  "$WIFI_AP" ]]; then
+			printhelp
+			exit
+		fi
 
-read -p "${CBLU}To: ${CDEF}" -ei "$RCPT " RCPT # opportunity to change destination
-read -p "${CBLU}From: ${CDEF}" -ei "$FROM " FROM # opportunity to change sender address
-
-[[ -z "$RCPT" ]] && out:fail 1 "FAIL: No recipient RCPT specified."
-
-RES="automatic email - see attached"
-
-read -p "${CBLU}Subject:${CDEF} " RES
-
-if [[ -n "$RES" ]]; then
-	"$EDITOR" "$MSGFILE"
-	if [[ -n "$GCMD" ]]; then
-		SIG=$(askuser:ask "Sign with GPG?")
-		[[ "$SIG" = y ]] && {
-			"$GCMD" --output="$ASCFILE" --clearsign "$MSGFILE"
-			MSGFILE="$ASCFILE"
+		oldconn "$WIFI_AP" || newconn "$WIFI_AP" "$WIFI_PW"
+		;;
+	forget)
+		WIFI_AP="$1"; shift
+		nmcli connection delete "$WIFI_AP" && {
+			out:info Done.
 		}
-	fi
-	mail -s "$RES" -r "$FROM" $FILES $RCPT < "$MSGFILE"
-fi
-
+		;;
+	list)
+		nmcli device wifi rescan
+		nmcli device wifi list
+		;;
+	old)
+		WIFI_AP="$1" ; shift
+		if [[ -z "$WIFI_AP" ]]; then
+			nmcli connection show|grep wireless
+		else
+			nmcli connection show "$WIFI_AP"|grep wireless
+		fi
+		;;
+	*)
+		out:fail "Invalid command $WIFICMD"
+		;;
+esac
diff --git a/src/sendme b/src/sendme
--- a/src/sendme
+++ b/src/sendme
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 ### sendme Usage:help
 # 
@@ -25,33 +25,36 @@
 # * specifying a template to use
 ###/doc
 
-#%include getbin autohelp bashout askuser
+#%include std/bincheck.sh
+#%include std/autohelp.sh
+#%include std/out.sh
+#%include std/askuser.sh
 
-GCMD="$(getbin gpg2 gpg)"
+GCMD="$(bincheck:get gpg2 gpg)"
 if [[ -z "${GCMD+x}" ]]; then
-	warne "No gpg2/gpg command found. Suggestion: install gnupg2"
+	out:warn "No gpg2/gpg command found. Suggestion: install gnupg2"
 elif [[ -z "$("$GCMD" --list-keys|egrep '^pub'|grep -v "expired")" ]]; then
-	warne "No GPG active keys currently installed ['$GCMD --list-keys']"
-	warne "Run '$GCMD --gen-key' to generate keys."
-	warne "---"
+	out:warn "No GPG active keys currently installed ['$GCMD --list-keys']"
+	out:warn "Run '$GCMD --gen-key' to generate keys."
+	out:warn "---"
 
 	# Treat as if no GPG support (do not prompt, etc)
 	GCMD=
 fi
 
 # FIXME prioritize with a stronger hash
-HASHCMD=$(getbin sha512sum sha256sum md5sum md5)
+HASHCMD=$(bincheck:get sha512sum sha256sum md5sum md5)
 
-if ! which mailx > /dev/null 2>&1; then
-	faile 96 "No mailx command found."
+if ! bincheck:has mailx; then
+	out:fail 96 "No mailx command found."
 fi
 
 if [[ -z "$EDITOR" ]]; then
-	if [[ -f /usr/bin/nano ]]; then
-		warne "\$EDITOR variable not set. Using nano"
-		export EDITOR=/usr/bin/nano
+	if bincheck:has nano; then
+		out:warn "\$EDITOR variable not set. Using nano"
+		export EDITOR="$(bincheck:get nano)"
 	else
-		faile 96 "\$EDITOR variable not set ; nano not available"
+		out:fail 96 "\$EDITOR variable not set ; nano not available"
 	fi
 fi
 
@@ -59,7 +62,7 @@ FILES=
 FROM=
 RCPT=
 ATCH=$( [[ $(man mailx | grep 'mailutils' -c) -gt 0 ]] && echo "-A" ; [[ $(man mailx | grep 'Heirloom' -c) -gt 0 ]] && echo "-a" ; )
-[[ -z "$ATCH" ]] && faile 96 "Could not determine mailx flavour."
+[[ -z "$ATCH" ]] && out:fail 96 "Could not determine mailx flavour."
 
 set -euo pipefail
 
@@ -71,18 +74,18 @@ ASCFILE="$MSGFILE.asc"
 [[ ! -z "$@" ]] && { echo -e "\n\n\n++++++\nAttachment [$HASHCMD] sums:\n" > "$MSGFILE" ; }
 
 for xfile in "$@"; do
-	[[ ! -f "$xfile" ]] && faile 2 "$xfile does not exist."
+	[[ ! -f "$xfile" ]] && out:fail 2 "$xfile does not exist."
 
 	FILES="$FILES $ATCH $xfile"
 	"$HASHCMD" "$xfile" >> "$MSGFILE"
 done
 
-[[ -z "$FILES" ]] && warne "No files specified"
+[[ -z "$FILES" ]] && out:warn "No files specified"
 
 read -p "${CBLU}To: ${CDEF}" -ei "$RCPT " RCPT # opportunity to change destination
 read -p "${CBLU}From: ${CDEF}" -ei "$FROM " FROM # opportunity to change sender address
 
-[[ -z "$RCPT" ]] && faile 1 "FAIL: No recipient RCPT specified."
+[[ -z "$RCPT" ]] && out:fail 1 "FAIL: No recipient RCPT specified."
 
 RES="automatic email - see attached"
 
@@ -91,7 +94,7 @@ read -p "${CBLU}Subject:${CDEF} " RES
 if [[ -n "$RES" ]]; then
 	"$EDITOR" "$MSGFILE"
 	if [[ -n "$GCMD" ]]; then
-		SIG=$(uask "Sign with GPG?")
+		SIG=$(askuser:ask "Sign with GPG?")
 		[[ "$SIG" = y ]] && {
 			"$GCMD" --output="$ASCFILE" --clearsign "$MSGFILE"
 			MSGFILE="$ASCFILE"
