Restart apache only on old connections; add delayed sending

diff --git a/modules/opconn/bin/stragglers-report b/modules/opconn/bin/stragglers-report
--- a/modules/opconn/bin/stragglers-report
+++ b/modules/opconn/bin/stragglers-report
@@ -14,6 +14,7 @@ else
 	exit 126
 fi
 
+# Configuration ===========
 # define SERVERNAME, FROM and RCPT
 CONFF="$HOME/.config/stragglers.conf"
 [[ -f "$CONFF" ]] && . "$CONFF"
@@ -23,13 +24,22 @@ CONFF="$HOME/.config/stragglers.conf"
 	exit 127
 }
 
+# Delayed sender =============
+
+for OPTS in $@; do
+if [[ "$OPTS" =~ "--send=" ]]; then
+	DESTFILE=${OPTS#--send=}
+	mailx -s "$SERVERNAME Stragglers report" -r "$FROM" "$RCPT" < "$DESTFILE"
+	if [[ $? -gt 0 ]]; then
+		echo "Could not get report file $DESTFILE"|mailx -s "$SERVERNAME stragglers - no report file" -r "$FROM" "$RCPT"
+	fi
+fi
+done
+
 # ============== Do it now
 
 if [[ -z "$CONNECTIONS" ]]; then
-	echo "Nothing to report."
 	exit
-else
-	echo "Generating and sending report for $CONNCOUNT connections."
 fi
 
 echo "$PORTSERV" | while read pserv; do
@@ -44,9 +54,11 @@ echo "$PORTSERV" | while read pserv; do
 done
 
 IPpat="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$" # I don't expect a wildly invalid IP to be returned by DNS tools...
-#IPpat2="^(([12]?)[0-9])?[0-9]\.(([12]?)[0-9])?[0-9]\.(([12]?)[0-9])?[0-9]\.(([12]?)[0-9])?[0-9]\.$" # more precise but I'm less sure of its validity
+
+# Print abuse information
 ABUSEF=/tmp/abuse
 echo "">$ABUSEF
+[[ 1 = 0 ]] && { # toggle
 echo "$SERVERS"|while read SERV ; do
 	[[ "$SERV" =~ $IPpat ]] || SERV=$(nslookup "$SERV" |egrep '^Name:' -A 1|grep 'Address:'|sed -r 's/Address:\s*//')
 	echo "$SERV" | while read myaddr; do # cater for: if it was a name resolved to multiple addresses
@@ -54,18 +66,22 @@ echo "$SERVERS"|while read SERV ; do
 		whois "$myaddr"|egrep -i '((net|name).+:)|(abuse.*:)|Abuse contact|OrgAbuseEmail|OrgName' >> "$ABUSEF"
 	done
 done
+}
 
 REPORTFILE="/tmp/report-$(date "+%F-%T")"
+
+if [[ $(stg_show|wc -l) -gt 1 ]]; then
 cat <<EOF > "$REPORTFILE"
 
 Report for $SERVERNAME
 
-Connections: $CONNCOUNT
+Old connections:
+
+$(stg_show)
 
 
 $(
-if [[ $(stg_show|wc -l) -gt 1 ]]; then
-	echo -e "	==== Apache Task ====\n\nRestarting apache\n"
+	echo -e "Restarting apache\n"
 	service apache2 restart 2>&1
 	if [[ $? -gt 0 ]]; then
 		service --status-all | mailx -s "URGENT - $SERVERNAME apache restart failed" -r "$FROM" "$RCPT"
@@ -73,26 +89,21 @@ if [[ $(stg_show|wc -l) -gt 1 ]]; then
 		stg_clearout
 		stg_drop # drop the now-obsolete old-connection artefacts
 	fi
-fi
+
 )
 
 	==== Servers involved ====
 
 $SERVERS
 
-	==== Abuse details ====
-
-$(cat $ABUSEF)
-
-	==== Ports to server ====
-
-$PORTSERV
-
 EOF
 
 if [[ "$@" =~ "--stdout" ]]; then
-	cat "$REPORTFILE" | less
+	cat "$REPORTFILE"
 else
 	cat "$REPORTFILE"   | mailx -s "$SERVERNAME Open connections: $CONNCOUNT" -r "$FROM" "$RCPT"
 fi
+
+fi # if stg_show greater than 1
+
 
