MANY changes
* The help is now taken from the readme
* No links support anymore - do it yourself
* No -to MOUNTPOINT support - just use the config
* split code out to other files
* added shim to palliate for a bug in bbuild which bundles incorrectly

diff --git a/projects/secure-dir/src/secdir b/projects/secure-dir/src/secdir
--- a/projects/secure-dir/src/secdir
+++ b/projects/secure-dir/src/secdir
@@ -18,91 +18,61 @@
 # IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 # WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 
+#% bundle README.md
+function printhelp {
+	cat README.md | sed -r 's/^(\s*\*)/\t\1/'
+}
 
-### secdir Usage:help
-# Manage, Mount and Unmount EncFS encrypted directory
-# 
-# 	secdir {list|init}
-# 	secdir {mount|open} ACCOUNT [-to MOUNTPOINT] [LINK ...]
-# 	secdir {unmount|close} ACCOUNT
-# 
-# Uses a ./secdir.enc directory in the current working directory to store the encrypted files.
-# 
-# The secure directory is mounted in the current working directory.
-# 
-# If you do not specify a MOUNTPOINT, creates a directory in the current working directory and mounts there, if allowed.
-# 
-# 
-# OPTIONS
-# 
-# list
-# 	list secure directories by account name configured at current working directory
-# 
-# init
-# 	set current working directory up as a location to store secure directories' encrypted data
-# 
-# {mount|open} [-to MOUNTPOINT] [LINKS ...]
-# 	mount the secure directory. If it does not exist, offers to create it.
-#
-# 	You can specify `-to MOUNTPOINT` to explicitly mount the directory at that location.
-#
-# 	You can specify any number of softlinks to create pointing to the mounted directory.
-#
-# 	Will fail if you cannot write to the mountpoint
-#
-# 	If you have configured against mounting in the current working directory, you MUST point the `-to MOUNTPOINT`
-# 	  to a different location. This allows secure directories to be distributed on a network
-# 	  whilst reducing the risk of a user indavertently mounting in a publicly shared directory.
-#
-# 	  This is a Molly-guard, NOT a security lock.
-# 
-# {unmount|close}
-# 	unmount a mounted secure directory.
-#
-# 	Any soft links created during mount will be removed.
-# 
-# CONFIGURATION
-# 
-# A configuration file is stored in secdir.enc/config. It is an INI-style key-value store
-# 
-# Crypt/utility
-# 	the name of the cryptographic utility to use
-# 	by default, encfs and cryfs are both supported
-# 	you can extend these with your own utilities in `./secdir.enc/crypts`
-#
-# Mount/load_in_cwd
-# 	yes --> allows mounting directories in current working directory
-# 	* --> do not allow
-# 
-# Mount/home
-# 	This must be a directory
-# 	By default secure directories are mounted here instead of in the current working directory
-###/doc 
+if [[ "$*" =~ --help ]]; then printhelp; exit 0; fi
 
 set -u
 
-#% include autohelp bashout abspath configreader
+#% include bashout abspath configreader askuser
 
 #% bundle files/config
-#% include files/linkage.sh
+# #% include files/linkage.sh
 
-if [[ "$1" = init ]]; then
+if [[ -z "$*" ]]; then
+	infoe "Nothing to do. Try running '$(basename "$0") --help' for more info"
+	exit
+fi
+
+ACTION="$1"; shift
+
+if [[ "$ACTION" = init ]]; then
+	:
 	#% include files/init-enc.sh
 fi
 
-if [[ ! -d "$HOME/.config/secdir" ]]; then
-	mkdir "$HOME/.config/secdir"
+# =======================================
+# Check that the current directory is a secdir directory
+
+if [[ ! -d "$PWD/secdir.enc" ]]; then
+	faile "Current directory $PWD is not a valid secdir location."
 fi
 
 CONFFILE=./secdir.enc/config
 MOUNTFILE="$HOME/.config/secdir/mounts" # make it global so we can close it from anywhere
 
+if [[ "$ACTION" = "list" ]] ; then
+	cd secdir.enc
+	infoe "Configured encryption utility: $(grep -o -P '(?<=utility=).+' "config")"
+	ownfiles='^(crypts|README.md|config)$'
+	for x in *; do
+		if [[ ! "$x" =~ $ownfiles ]]; then
+			echo "$x"
+		fi
+	done
+	exit
+fi
+
+
 #% bundle crypts/encfs.crypt.source
 #% bundle crypts/cryfs.crypt.source
-if [[ ! -d "$HOME/.config/secdir/crypts" ]] || [[ "$*" =~ --installcrypts ]]; then
-	mkdir -p "$HOME/.config/secdir/crypts"
-	cp crypts/encfs.crypt.source "$HOME/.config/secdir/crypts/"
-	cp crypts/cryfs.crypt.source "$HOME/.config/secdir/crypts/"
+if [[ ! -d "./secdir.enc/crypts" ]] || [[ "$*" =~ --installcrypts ]]; then
+	mkdir -p "./secdir.enc/crypts"
+	cp crypts/encfs.crypt.source "./secdir.enc/crypts/"
+	cp crypts/cryfs.crypt.source "./secdir.enc/crypts/"
 fi
 
 # =============================
@@ -121,8 +91,8 @@ if ! config_isset utility; then
 	faile "No encryption utility specified in secdir.enc/config"
 else
 	cryptutil=$(config_readval utility)
-	if [[ -f "$HOME/.config/secdir/crypts/$cryptutil.crypt.source" ]]; then
-		source "$HOME/.config/secdir/crypts/$cryptutil.crypt.source"
+	if [[ -f "./secdir.enc/crypts/$cryptutil.crypt.source" ]]; then
+		source "./secdir.enc/crypts/$cryptutil.crypt.source"
 	else
 		faile "Encryption utility '$cryptutil' not defined"
 	fi
@@ -142,25 +112,25 @@ fi
 # stops at first non-option-flag
 #% include files/swallow-options.source
 
-if [[ "$1" = list ]]; then
-	#% include files/listall.sh
-	exit 0
-fi
-
 
 if [[ ! -f "$MOUNTFILE" ]]; then
 	touch "$MOUNTFILE" || faile "Cannot create $MOUNTFILE"
+fi
+
+# ====
+# Swallow optional options
+# stops at first non-option-flag
+#% include files/swallow-options.source
+
+
+if [[ -z "$*" ]]; then
+	faile "You must specify the name of a secure directory to load"
 fi
 
 # ====================================
 # Get the secured directory
 
 CUST="$1" ; shift
-
-# ====
-# Swallow optional options
-# stops at first non-option-flag
-#% include files/swallow-options.source
 
 case "$ACTION" in
 	mount|open)
@@ -171,20 +141,24 @@ case "$ACTION" in
 		mountpointdir=
 		if grep -E "^$CUST:" "$MOUNTFILE" -q; then
 			mountpointdir="$(grep -E "^$CUST:" "$MOUNTFILE"|cut -d':' -f2)"
-		elif grep -E "$CUST" "$MOUNTFILE"
+		elif grep -E "$CUST" "$MOUNTFILE"; then
 			mountpointdir="$CUST"
 		else
 			faile "$CUST is neither a secure-profile or a recognized mounted location."
 		fi
 
+		#if [[ -f "$PWD/secdir.enc/${CUST}.links" ]]; then
+		#	infoe "Unlinking registered soft links"
+		#	dlinkall || {
+		#		warne "Could not unlink some directories:$(echo; cat "$PWD/secdir.enc/${CUST}.links")"
+		#		uconfirm "Unmount anyway?" || faile "Failed to unlink, aborting."
+		#	}
+		#fi
+
 		infoe "Closing $CUST"
-		if delinkall ; then # or, 'if delinkall is successfule, then:'
-			_close_crypt "$mountpointdir" || faile "Could not close $CUST"
-			rmdir "$mountpointdir"
-			sed "/^$CUST:/d" -i "$MOUNTFILE"
-		else
-			faile "Could not unlink some directories:$(echo; cat "$PWD/secdir.enc/${CUST}.links")" 3
-		fi
+		_close_crypt "$mountpointdir" || faile "Could not close $CUST"
+		rmdir "$mountpointdir"
+		sed -r "/(^$CUST:|:$CUST$)/d" -i "$MOUNTFILE"
 		;;
 
 
@@ -193,3 +167,5 @@ case "$ACTION" in
 		faile "Invalid action [$ACTION]. See --help for more information"
 		;;
 esac
+
+#% bundle files/config
